"""Loopback fault server. Only generated bytes; deliberately not an OpenList emulator."""
from __future__ import annotations

import hashlib
import json
import threading
import time
import urllib.parse
import xml.etree.ElementTree as ET
from contextlib import contextmanager
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


MEDIA_BYTES = bytes((i * 37 + i // 251) % 256 for i in range(131077))
SRT = b"1\n00:00:00,100 --> 00:00:01,500\nGenerated subtitle\n"


class MockDAV:
    def __init__(self):
        self.files = {"/": None, "/tests": None, "/media.bin": MEDIA_BYTES}
        self.faults = {}
        self.requests = []
        self.redirect_target = None
        self.url = ""


@contextmanager
def mock_server():
    state = MockDAV()

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *args):
            pass

        def reply(self, status, data=b"", headers=None):
            self.send_response(status)
            for key, value in (headers or {}).items():
                self.send_header(key, value)
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            try:
                self.wfile.write(data)
            except (BrokenPipeError, ConnectionError):
                pass

        def record(self):
            self.path_key = urllib.parse.unquote(urllib.parse.urlsplit(self.path).path).rstrip("/") or "/"
            state.requests.append((self.command, self.path_key, dict(self.headers)))
            length = int(self.headers.get("Content-Length", "0"))
            return self.rfile.read(length) if length else b""

        def do_PROPFIND(self):
            self.record()
            path = self.path_key
            if state.faults.get(path) == "permission":
                self.reply(403)
                return
            if path not in state.files:
                self.reply(404)
                return
            root = ET.Element("{DAV:}multistatus")
            names = [path]
            if self.headers.get("Depth") == "1":
                names += [name for name in state.files if name != path and
                          name.rsplit("/", 1)[0] == path.rstrip("/")]
            for name in names:
                node = ET.SubElement(root, "{DAV:}response")
                ET.SubElement(node, "{DAV:}href").text = urllib.parse.quote(name, safe="/")
                propstat = ET.SubElement(node, "{DAV:}propstat")
                code = 403 if state.faults.get(path) == "property_permission" else 200
                ET.SubElement(propstat, "{DAV:}status").text = f"HTTP/1.1 {code} Test"
                props = ET.SubElement(propstat, "{DAV:}prop")
                kind = ET.SubElement(props, "{DAV:}resourcetype")
                content = state.files[name]
                if content is None:
                    ET.SubElement(kind, "{DAV:}collection")
                else:
                    ET.SubElement(props, "{DAV:}getcontentlength").text = str(len(content))
                    ET.SubElement(props, "{DAV:}getetag").text = '"' + hashlib.sha256(content).hexdigest() + '"'
                ET.SubElement(props, "{DAV:}getlastmodified").text = "Thu, 08 Oct 2026 00:00:00 GMT"
                # Optional missing properties are normal, unlike a denied response item.
                missing = ET.SubElement(node, "{DAV:}propstat")
                ET.SubElement(missing, "{DAV:}status").text = "HTTP/1.1 404 Not Found"
                ET.SubElement(ET.SubElement(missing, "{DAV:}prop"), "{DAV:}displayname")
            self.reply(207, ET.tostring(root))

        def do_MKCOL(self):
            self.record()
            if self.path_key in state.files:
                self.reply(405)
            elif self.path_key.rsplit("/", 1)[0] not in state.files:
                self.reply(409)
            else:
                state.files[self.path_key] = None
                self.reply(201)

        def do_PUT(self):
            content = self.record()
            if state.faults.get(self.path_key) == "permission":
                self.reply(403)
            elif self.path_key in state.files and self.headers.get("If-None-Match") == "*":
                self.reply(412)
            else:
                state.files[self.path_key] = (b"!" * len(content) if state.faults.get(self.path_key) == "corrupt_put_same_size"
                                            else content + (b"!" if state.faults.get(self.path_key) == "corrupt_put" else b""))
                self.reply(201)

        def do_GET(self):
            self.record()
            path = self.path_key
            if path in {"/redirect", "/cross-redirect"}:
                self.reply(302, headers={"Location": state.redirect_target or state.url + "media.bin"})
                return
            if path == "/subtitle.srt":
                self.reply(200, SRT)
                return
            if path not in state.files or state.files[path] is None:
                self.reply(404)
                return
            content = state.files[path]
            fault = state.faults.get(path)
            expected_etag = '"' + hashlib.sha256(content).hexdigest() + '"'
            if self.headers.get("If-Match", expected_etag) != expected_etag:
                self.reply(412)
                return
            if "Range" not in self.headers or fault == "range_ignored":
                self.reply(200, content)
                return
            start, end = map(int, self.headers["Range"].removeprefix("bytes=").split("-"))
            data = content[start:end + 1]
            if fault == "short_range":
                data = data[:-1]
            if fault == "short_body":
                self.send_response(206)
                self.send_header("Content-Length", str(len(data)))
                self.send_header("Content-Range", f"bytes {start}-{end}/{len(content)}")
                self.end_headers()
                self.wfile.write(data[:-1])
                self.close_connection = True
                return
            shift = 1 if fault == "wrong_range" else 0
            self.reply(206, data, {"Content-Range": f"bytes {start + shift}-{end + shift}/{len(content)}"})
            if fault == "source_changes":
                state.files[path] = content + b"!"

        def do_POST(self):
            self.record()
            if self.path_key == "/shooter-no-match":
                self.reply(200, b"\xff")
            elif self.path_key == "/shooter-failure":
                self.reply(503)
            elif self.path_key == "/shooter-timeout":
                time.sleep(0.25)
                self.reply(200, b"[]")
            else:
                candidates = [{"Delay": 0, "Files": [{"Ext": "srt", "Link": state.url + "subtitle.srt"}]}]
                self.reply(200, json.dumps(candidates).encode())

        def do_MOVE(self):
            self.record()
            source = self.path_key
            target = urllib.parse.unquote(urllib.parse.urlsplit(self.headers.get("Destination", "")).path).rstrip("/")
            fault = state.faults.get(source)
            if self.headers.get("Overwrite") != "F":
                self.reply(400)
                return
            if fault == "permission":
                self.reply(403)
                return
            if target in state.files:
                self.reply(500 if fault == "conflict500" else 412)
                return
            if fault == "partial_move":
                state.files[target] = None
                self.reply(207, b'<d:multistatus xmlns:d="DAV:"><d:response><d:href>/child</d:href><d:status>HTTP/1.1 403 Forbidden</d:status></d:response></d:multistatus>')
                return
            if fault != "timeout_before":
                for name in list(state.files):
                    if name == source or name.startswith(source + "/"):
                        state.files[target + name[len(source):]] = state.files.pop(name)
            if fault in {"timeout_after", "timeout_before"}:
                time.sleep(0.25)
            self.reply(201)

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    server.daemon_threads = True
    state.url = f"http://127.0.0.1:{server.server_port}/"
    thread = threading.Thread(target=server.serve_forever, kwargs={"poll_interval": 0.02}, daemon=True)
    thread.start()
    try:
        yield state
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2)
