from typing import Protocol

from reeldock.domain import (
    Artwork,
    Episode,
    Movie,
    Person,
    RemoteEntry,
    Season,
    Series,
    SubtitleCandidate,
)


class StorageProvider(Protocol):
    async def list(self, path: str) -> list[RemoteEntry]: ...
    async def stat(self, path: str) -> RemoteEntry: ...
    async def read_small(self, path: str, max_bytes: int) -> bytes: ...
    async def read_range(self, path: str, start: int, length: int, size: int) -> bytes: ...
    async def put(self, path: str, content: bytes) -> None: ...
    async def mkdir(self, path: str) -> None: ...
    async def move(self, source: str, target: str) -> None: ...
    async def capabilities(self) -> dict[str, bool]: ...


class MetadataProvider(Protocol):
    async def search(self, query: str, kind: str, year: int | None = None) -> list[Movie]: ...
    async def find_movie(self, imdb_id: str) -> Movie: ...
    async def movie_details(self, external_id: str) -> Movie: ...
    async def series_details(self, external_id: str) -> Series: ...
    async def season_details(self, external_id: str, season: int) -> Season: ...
    async def episode_details(self, external_id: str, season: int, episode: int) -> Episode: ...
    async def credits(self, external_id: str, kind: str) -> list[Person]: ...
    async def images(self, external_id: str, kind: str) -> list[Artwork]: ...
    async def download_artwork(self, artwork: Artwork) -> bytes: ...


class SubtitleProvider(Protocol):
    async def search(
        self, fingerprint: str, episode_context: dict | None
    ) -> list[SubtitleCandidate]: ...
    async def download(self, candidate: SubtitleCandidate) -> bytes: ...
